-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.dim_cuaca
(
    id_cuaca integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    kondisi_cuaca character varying(50) COLLATE pg_catalog."default",
    suhu_min double precision,
    suhu_max double precision,
    curah_hujan double precision,
    kelembaban double precision,
    CONSTRAINT dim_cuaca_pkey PRIMARY KEY (id_cuaca)
);

CREATE TABLE IF NOT EXISTS public.dim_event
(
    id_event integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nama_event character varying(100) COLLATE pg_catalog."default",
    jenis_event character varying(50) COLLATE pg_catalog."default",
    target_pengunjung character varying(100) COLLATE pg_catalog."default",
    tanggal_event date,
    CONSTRAINT dim_event_pkey PRIMARY KEY (id_event)
);

CREATE TABLE IF NOT EXISTS public.dim_kategori_pengunjung
(
    id_kategori_pengunjung integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nama_kategori character varying(50) COLLATE pg_catalog."default",
    rentang_usia character varying(20) COLLATE pg_catalog."default",
    domisili character varying(100) COLLATE pg_catalog."default",
    preferensi character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT dim_kategori_pengunjung_pkey PRIMARY KEY (id_kategori_pengunjung)
);

CREATE TABLE IF NOT EXISTS public.dim_log_air
(
    id_log_air integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    debit_air double precision,
    ph double precision,
    turbidity integer,
    tds integer,
    tanggal_ukur date,
    CONSTRAINT dim_log_air_pkey PRIMARY KEY (id_log_air)
);

CREATE TABLE IF NOT EXISTS public.dim_operasioanl
(
    id_operasional integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    jenis_biaya character varying(100) COLLATE pg_catalog."default",
    vendor character varying(50) COLLATE pg_catalog."default",
    biaya integer,
    CONSTRAINT dim_operasioanl_pkey PRIMARY KEY (id_operasional)
);

CREATE TABLE IF NOT EXISTS public.dim_platform
(
    id_platform integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nama_platform character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT dim_platform_pkey PRIMARY KEY (id_platform)
);

CREATE TABLE IF NOT EXISTS public.dim_promosi
(
    id_promosi integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nama_promosi character varying(100) COLLATE pg_catalog."default",
    jenis_promosi character varying(50) COLLATE pg_catalog."default",
    deskripsi text COLLATE pg_catalog."default",
    periode_start date,
    periode_end date,
    CONSTRAINT dim_promosi_pkey PRIMARY KEY (id_promosi)
);

CREATE TABLE IF NOT EXISTS public.dim_property
(
    id_property integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nama_property character varying(100) COLLATE pg_catalog."default",
    tipe_property character varying(50) COLLATE pg_catalog."default",
    kondisi character varying(50) COLLATE pg_catalog."default",
    status_kepemilikan character varying(50) COLLATE pg_catalog."default",
    jumlah_property integer,
    bahan_dasar character varying(50) COLLATE pg_catalog."default",
    maintenance_terakhir date,
    CONSTRAINT dim_property_pkey PRIMARY KEY (id_property)
);

CREATE TABLE IF NOT EXISTS public.dim_stand
(
    id_stand integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nama_stand character varying(100) COLLATE pg_catalog."default",
    kategori_stand character varying(50) COLLATE pg_catalog."default",
    lokasi_stand character varying(100) COLLATE pg_catalog."default",
    pemilik_stand character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT dim_stand_pkey PRIMARY KEY (id_stand)
);

CREATE TABLE IF NOT EXISTS public.dim_telaga
(
    id_telaga integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nama_telaga character varying(100) COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default",
    deskripsi character varying(200) COLLATE pg_catalog."default",
    kapasitas integer,
    CONSTRAINT dim_telaga_pkey PRIMARY KEY (id_telaga)
);

CREATE TABLE IF NOT EXISTS public.dim_ulasan
(
    id_ulasan integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    platform character varying(100) COLLATE pg_catalog."default",
    rating real,
    isi_ulasan character varying(200) COLLATE pg_catalog."default",
    tanggal_ulasan date,
    CONSTRAINT dim_ulasan_pkey PRIMARY KEY (id_ulasan)
);

CREATE TABLE IF NOT EXISTS public.dim_waktu
(
    id_waktu integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    tanggal date,
    hari character varying(20) COLLATE pg_catalog."default",
    bulan integer,
    tahun integer,
    kuartal integer,
    minggu_ke integer,
    is_libur boolean,
    CONSTRAINT dim_waktu_pkey PRIMARY KEY (id_waktu)
);

CREATE TABLE IF NOT EXISTS public.fact_air
(
    id_air_log serial NOT NULL,
    id_waktu integer,
    id_telaga integer,
    debit_air double precision,
    ph double precision,
    turbidity double precision,
    tds double precision,
    suhu_air double precision,
    CONSTRAINT fact_air_pkey PRIMARY KEY (id_air_log)
);

CREATE TABLE IF NOT EXISTS public.fact_event
(
    id_event_fakta serial NOT NULL,
    id_event integer,
    id_waktu integer,
    id_telaga integer,
    jumlah_pengunjung_event integer,
    biaya_event integer,
    CONSTRAINT fact_event_pkey PRIMARY KEY (id_event_fakta)
);

CREATE TABLE IF NOT EXISTS public.fact_keuangan
(
    id_keuangan serial NOT NULL,
    id_waktu integer,
    id_telaga integer,
    pemasukan_tiket integer,
    pemasukan_stand integer,
    biaya_operasional integer,
    biaya_promosi integer,
    biaya_event integer,
    tagihan_listrik integer,
    tagihan_air integer,
    laba_rugi_total integer,
    CONSTRAINT fact_keuangan_pkey PRIMARY KEY (id_keuangan)
);

CREATE TABLE IF NOT EXISTS public.fact_kunjungan_telaga
(
    id_fact_kunjungan serial NOT NULL,
    tanggal date NOT NULL,
    jumlah_pengunjung integer,
    kapasitas_terpakai integer,
    id_dim_telaga integer,
    id_dim_event integer,
    id_dim_cuaca integer,
    id_dim_promosi integer,
    id_dim_waktu integer,
    CONSTRAINT fact_kunjungan_telaga_pkey PRIMARY KEY (id_fact_kunjungan)
);

CREATE TABLE IF NOT EXISTS public.fact_operasional
(
    id_fact_operasional serial NOT NULL,
    tanggal date NOT NULL,
    total_biaya integer,
    id_dim_operasioanl integer,
    id_dim_property integer,
    id_dim_waktu integer,
    CONSTRAINT fact_operasional_pkey PRIMARY KEY (id_fact_operasional)
);

CREATE TABLE IF NOT EXISTS public.fact_property
(
    id_properti_harian serial NOT NULL,
    id_waktu integer,
    id_properti integer,
    id_telaga integer,
    jumlah_property integer,
    CONSTRAINT fact_property_pkey PRIMARY KEY (id_properti_harian)
);

CREATE TABLE IF NOT EXISTS public.fact_segmentasi_pengunjung
(
    id_fact_pengunjung serial NOT NULL,
    tanggal date NOT NULL,
    jumlah_pengunjung integer,
    id_dim_promosi integer,
    id_dim_event integer,
    id_dim_cuaca integer,
    id_dim_kategori_pengunjung integer,
    id_dim_waktu integer,
    CONSTRAINT fact_segmentasi_pengunjung_pkey PRIMARY KEY (id_fact_pengunjung)
);

CREATE TABLE IF NOT EXISTS public.fact_stand
(
    id_transaksi_stand serial NOT NULL,
    id_stand integer,
    id_waktu integer,
    id_telaga integer,
    pendapatan_per_hari integer,
    lama_sewa integer,
    biaya_sewa integer,
    CONSTRAINT fact_stand_pkey PRIMARY KEY (id_transaksi_stand)
);

CREATE TABLE IF NOT EXISTS public.fact_ulasan
(
    id_ulasan_fakta serial NOT NULL,
    id_ulasan integer,
    id_platform integer,
    id_waktu integer,
    id_telaga integer,
    CONSTRAINT fact_ulasan_pkey PRIMARY KEY (id_ulasan_fakta)
);

ALTER TABLE IF EXISTS public.fact_air
    ADD CONSTRAINT fact_air_id_telaga_fkey FOREIGN KEY (id_telaga)
    REFERENCES public.dim_telaga (id_telaga) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_air
    ADD CONSTRAINT fact_air_id_waktu_fkey FOREIGN KEY (id_waktu)
    REFERENCES public.dim_waktu (id_waktu) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_event
    ADD CONSTRAINT fact_event_id_event_fkey FOREIGN KEY (id_event)
    REFERENCES public.dim_event (id_event) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_event
    ADD CONSTRAINT fact_event_id_telaga_fkey FOREIGN KEY (id_telaga)
    REFERENCES public.dim_telaga (id_telaga) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_event
    ADD CONSTRAINT fact_event_id_waktu_fkey FOREIGN KEY (id_waktu)
    REFERENCES public.dim_waktu (id_waktu) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_keuangan
    ADD CONSTRAINT fact_keuangan_id_telaga_fkey FOREIGN KEY (id_telaga)
    REFERENCES public.dim_telaga (id_telaga) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_keuangan
    ADD CONSTRAINT fact_keuangan_id_waktu_fkey FOREIGN KEY (id_waktu)
    REFERENCES public.dim_waktu (id_waktu) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_kunjungan_telaga
    ADD CONSTRAINT fact_kunjungan_telaga_id_dim_cuaca_fkey FOREIGN KEY (id_dim_cuaca)
    REFERENCES public.dim_cuaca (id_cuaca) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_kunjungan_telaga
    ADD CONSTRAINT fact_kunjungan_telaga_id_dim_event_fkey FOREIGN KEY (id_dim_event)
    REFERENCES public.dim_event (id_event) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_kunjungan_telaga
    ADD CONSTRAINT fact_kunjungan_telaga_id_dim_promosi_fkey FOREIGN KEY (id_dim_promosi)
    REFERENCES public.dim_promosi (id_promosi) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_kunjungan_telaga
    ADD CONSTRAINT fact_kunjungan_telaga_id_dim_telaga_fkey FOREIGN KEY (id_dim_telaga)
    REFERENCES public.dim_telaga (id_telaga) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_kunjungan_telaga
    ADD CONSTRAINT fact_kunjungan_telaga_id_dim_waktu_fkey FOREIGN KEY (id_dim_waktu)
    REFERENCES public.dim_waktu (id_waktu) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_operasional
    ADD CONSTRAINT fact_operasional_id_dim_operasioanl_fkey FOREIGN KEY (id_dim_operasioanl)
    REFERENCES public.dim_operasioanl (id_operasional) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_operasional
    ADD CONSTRAINT fact_operasional_id_dim_property_fkey FOREIGN KEY (id_dim_property)
    REFERENCES public.dim_property (id_property) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_operasional
    ADD CONSTRAINT fact_operasional_id_dim_waktu_fkey FOREIGN KEY (id_dim_waktu)
    REFERENCES public.dim_waktu (id_waktu) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_property
    ADD CONSTRAINT fact_property_id_properti_fkey FOREIGN KEY (id_properti)
    REFERENCES public.dim_property (id_property) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_property
    ADD CONSTRAINT fact_property_id_telaga_fkey FOREIGN KEY (id_telaga)
    REFERENCES public.dim_telaga (id_telaga) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_property
    ADD CONSTRAINT fact_property_id_waktu_fkey FOREIGN KEY (id_waktu)
    REFERENCES public.dim_waktu (id_waktu) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_segmentasi_pengunjung
    ADD CONSTRAINT fact_segmentasi_pengunjung_id_dim_cuaca_fkey FOREIGN KEY (id_dim_cuaca)
    REFERENCES public.dim_cuaca (id_cuaca) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_segmentasi_pengunjung
    ADD CONSTRAINT fact_segmentasi_pengunjung_id_dim_event_fkey FOREIGN KEY (id_dim_event)
    REFERENCES public.dim_event (id_event) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_segmentasi_pengunjung
    ADD CONSTRAINT fact_segmentasi_pengunjung_id_dim_kategori_pengunjung_fkey FOREIGN KEY (id_dim_kategori_pengunjung)
    REFERENCES public.dim_kategori_pengunjung (id_kategori_pengunjung) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_segmentasi_pengunjung
    ADD CONSTRAINT fact_segmentasi_pengunjung_id_dim_promosi_fkey FOREIGN KEY (id_dim_promosi)
    REFERENCES public.dim_promosi (id_promosi) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_segmentasi_pengunjung
    ADD CONSTRAINT fact_segmentasi_pengunjung_id_dim_waktu_fkey FOREIGN KEY (id_dim_waktu)
    REFERENCES public.dim_waktu (id_waktu) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_stand
    ADD CONSTRAINT fact_stand_id_stand_fkey FOREIGN KEY (id_stand)
    REFERENCES public.dim_stand (id_stand) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_stand
    ADD CONSTRAINT fact_stand_id_telaga_fkey FOREIGN KEY (id_telaga)
    REFERENCES public.dim_telaga (id_telaga) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_stand
    ADD CONSTRAINT fact_stand_id_waktu_fkey FOREIGN KEY (id_waktu)
    REFERENCES public.dim_waktu (id_waktu) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_ulasan
    ADD CONSTRAINT fact_ulasan_id_platform_fkey FOREIGN KEY (id_platform)
    REFERENCES public.dim_platform (id_platform) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_ulasan
    ADD CONSTRAINT fact_ulasan_id_telaga_fkey FOREIGN KEY (id_telaga)
    REFERENCES public.dim_telaga (id_telaga) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_ulasan
    ADD CONSTRAINT fact_ulasan_id_ulasan_fkey FOREIGN KEY (id_ulasan)
    REFERENCES public.dim_ulasan (id_ulasan) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_ulasan
    ADD CONSTRAINT fact_ulasan_id_waktu_fkey FOREIGN KEY (id_waktu)
    REFERENCES public.dim_waktu (id_waktu) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;